sudo: required

services:
  - docker

before_install:
  - docker build -t adrianorft/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adrianorft/react-test npm run test

after_success:
  - docker build -t adrianorft/multi-client ./client
  - docker build -t adrianorft/multi-nginx ./nginx
  - docker build -t adrianorft/multi-server ./server
  - docker build -t adrianorft/multi-worker ./worker
# Push images to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adrianorft/multi-client
  - docker push adrianorft/multi-nginx
  - docker push adrianorft/multi-server
  - docker push adrianorft/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-356794932707"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# access_key_id: $AWS_ACCESS_KEY
# secret_access_key: $AWS_SECRET_KEY

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   ...